[project]
name = 'Galactic-Civilization'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.civilization-management]
path = 'contracts/civilization-management.clar'
clarity_version = 2
epoch = 2.5

[contracts.technology-advancement]
path = 'contracts/technology-advancement.clar'
clarity_version = 2
epoch = 2.5
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
